if (MSVC)
  add_compile_options (/WX /W4)
else ()
  add_compile_options (-Wall)
  add_compile_options (-Wconversion)
  add_compile_options (-Wctor-dtor-privacy)
  add_compile_options (-Wdouble-promotion)
  add_compile_options (-Weffc++)
  add_compile_options (-Werror)
  add_compile_options (-Wextra)
  add_compile_options (-Wextra-semi)
  add_compile_options (-Wfloat-equal)
  add_compile_options (-Wformat=2)
  add_compile_options (-Wimplicit-fallthrough)
  add_compile_options (-Wmisleading-indentation)
  add_compile_options (-Wmissing-declarations)
  add_compile_options (-Wnon-virtual-dtor)
  add_compile_options (-Wnull-dereference)
  add_compile_options (-Wold-style-cast)
  add_compile_options (-Woverloaded-virtual)
  add_compile_options (-Wpedantic)
  add_compile_options (-Wredundant-decls)
  add_compile_options (-Wshadow)
  add_compile_options (-Wsign-conversion)
  add_compile_options (-Wundef)
  add_compile_options (-Wunused)
  add_compile_options (-Wzero-as-null-pointer-constant)

  add_compile_options (-fdiagnostics-color=always)
  add_compile_options (-pedantic)

  if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    # add_compile_options (-stdlib=libc++) # Results in error: `cmath` not found
  else()
    add_compile_options (-Wduplicated-branches)
    add_compile_options (-Wduplicated-cond)
    add_compile_options (-Wlogical-op)
    add_compile_options (-Wstrict-null-sentinel)
    add_compile_options (-Wuseless-cast)
  endif()
endif ()

